services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: brainjam
      POSTGRES_PASSWORD: brainjam
      POSTGRES_DB: brainjam
    ports:
      - "5432:5432"
    volumes:
      - brainjam_pg:/var/lib/postgresql/data

volumes:
  brainjam_pg:
