"""init schema

Revision ID: 51646340c789
Revises: 
Create Date: 2026-05-17 15:59:00.038379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51646340c789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puzzle_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_packs_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('puzzle_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puzzle_pack_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_pack_id'], ['puzzle_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puzzle_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_tasks_puzzle_pack_id'), ['puzzle_pack_id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_pack_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('LOBBY', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='room_status'), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['puzzle_pack_id'], ['puzzle_packs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_rooms_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_puzzle_pack_id'), ['puzzle_pack_id'], unique=False)

    op.create_table('room_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'PLAYER', 'SPECTATOR', name='room_role'), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_members_room_user')
    )
    with op.batch_alter_table('room_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_members_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_members_user_id'), ['user_id'], unique=False)

    op.create_table('room_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_task_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='room_task_status'), nullable=False),
    sa.Column('submitted_answer', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['puzzle_task_id'], ['puzzle_tasks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_tasks_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_tasks_puzzle_task_id'), ['puzzle_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_tasks_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_tasks_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_tasks_puzzle_task_id'))
        batch_op.drop_index(batch_op.f('ix_room_tasks_assigned_to_id'))

    op.drop_table('room_tasks')
    with op.batch_alter_table('room_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_members_room_id'))

    op.drop_table('room_members')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_puzzle_pack_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_owner_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_invite_code'))

    op.drop_table('rooms')
    with op.batch_alter_table('puzzle_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_tasks_puzzle_pack_id'))

    op.drop_table('puzzle_tasks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('puzzle_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_packs_slug'))

    op.drop_table('puzzle_packs')
    # ### end Alembic commands ###
